const requests=[
 {id:'RF-2048',name:'Abena Owusu',phone:'+233 24 611 8432',loc:'Twifo Praso',bags:30,type:'Pickup',date:'Today, 10:44',status:'pending',initials:'AO',color:'pink'},
 {id:'RF-2047',name:'Yaw Boateng',phone:'+233 54 221 8870',loc:'Assin Fosu',bags:18,type:'Delivery',date:'Today, 10:31',status:'pending',initials:'YB',color:'orange'},
 {id:'RF-2046',name:'Esi Kwarteng',phone:'+233 20 182 5301',loc:'Dunkwa',bags:24,type:'Pickup',date:'Today, 09:58',status:'transit',initials:'EK',color:'teal'},
 {id:'RF-2045',name:'Kofi Antwi',phone:'+233 24 730 2291',loc:'Cape Coast',bags:12,type:'Delivery',date:'Today, 09:15',status:'assigned',initials:'KA',color:'purple'},
 {id:'RF-2044',name:'Ama Serwaa',phone:'+233 27 921 3822',loc:'Jukwa',bags:40,type:'Pickup',date:'Yesterday',status:'transit',initials:'AS',color:'orange'}];
const statusText={pending:'Pending review',assigned:'Driver assigned',transit:'In transit'};
const inbox=document.querySelector('#inbox-list'),table=document.querySelector('#request-table');
function avatar(r){return `<span class="avatar ${r.color}">${r.initials}</span>`}
function render(){if(inbox)inbox.innerHTML=requests.slice(0,3).map(r=>`<div class="request-item">${avatar(r)}<div><h3>${r.name}</h3><p>${r.loc} · ${r.type} · ${r.bags} bags</p></div><div><span class="badge ${r.status}">${statusText[r.status]}</span><p class="request-meta">${r.date}</p></div></div>`).join('');if(table)table.innerHTML=requests.map(r=>`<tr data-status="${r.status}"><td><b>${r.name}</b><small>${r.phone}</small></td><td><b>${r.bags} bags · ${r.type}</b><small>${r.id}</small></td><td>${r.loc}</td><td>${r.date}</td><td><span class="badge ${r.status}">${statusText[r.status]}</span></td><td>${r.status==='pending'?`<button class="row-link assign" data-id="${r.id}">Review →</button>`:'<button class="row-link">View →</button>'}</td></tr>`).join('');}
render();
document.querySelectorAll('.nav-item').forEach(btn=>btn.onclick=()=>showView(btn.dataset.view));document.querySelectorAll('[data-go]').forEach(btn=>btn.onclick=()=>showView(btn.dataset.go));
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));document.querySelector('#page-name').textContent=id==='farmer'?'WHATSAPP INTAKE':id.toUpperCase();window.scrollTo({top:0,behavior:'smooth'});}
function toast(msg){document.querySelector('#toast-text').textContent=msg;const el=document.querySelector('#toast');el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3500)}
document.querySelector('#notify-btn').onclick=()=>toast('3 unread updates: 2 farmer requests and 1 driver status.');
function addRequest(){const r={id:'RF-2049',name:'Akosua Darko',phone:'+233 50 449 1820',loc:'Elmina Road',bags:22,type:'Pickup',date:'Just now',status:'pending',initials:'AD',color:'purple'};if(!requests.some(x=>x.id===r.id)){requests.unshift(r);render();document.querySelector('#request-count').textContent='4';document.querySelector('#bell-count').textContent='4';document.querySelector('#open-metric').textContent='09';toast('New request received from Akosua Darko via WhatsApp');}showView('requests')}
document.querySelector('#simulate-request').onclick=addRequest;document.querySelector('#new-request').onclick=addRequest;document.querySelector('#open-chat').onclick=()=>toast('WhatsApp preview opened — this mock flow collects farmer details automatically.');
document.querySelectorAll('.filter').forEach(f=>f.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));f.classList.add('active');document.querySelectorAll('#request-table tr').forEach(row=>row.style.display=f.dataset.filter==='all'||row.dataset.status===f.dataset.filter?'':'none')});
document.addEventListener('click',e=>{const id=e.target.dataset.id;if(e.target.classList.contains('assign')&&id){const r=requests.find(x=>x.id===id);document.querySelector('#assign-info').innerHTML=`<b>${r.name}</b><br>${r.loc} · ${r.type} · ${r.bags} bags`;document.querySelector('#assign-modal').dataset.id=id;document.querySelector('#assign-modal').classList.add('show')}if(e.target.classList.contains('close'))document.querySelector('#assign-modal').classList.remove('show');});
document.querySelector('#confirm-assign').onclick=()=>{const r=requests.find(x=>x.id===document.querySelector('#assign-modal').dataset.id);r.status='assigned';render();document.querySelector('#assign-modal').classList.remove('show');toast(`Dennis Asare assigned — WhatsApp notification sent to ${r.name}`)};
